# Generated by Django 5.1.2 on 2024-10-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tblusers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('strname', models.CharField(max_length=400)),
                ('strmidname', models.CharField(max_length=400)),
                ('strlastname', models.CharField(max_length=400)),
                ('strlogin', models.CharField(max_length=400)),
                ('strpassword', models.CharField(max_length=256)),
                ('stremail', models.CharField(max_length=400)),
                ('strphone', models.CharField(max_length=20)),
                ('blnactive', models.BooleanField()),
                ('dtmupdate', models.DateTimeField()),
            ],
        ),
    ]
